### ISSUE TITLE
Is ComponentRouter "restrict: 'E' "

### ISSUE THREAD

**Issue by albatrosary** [excellalabs/ngComponentRouter#1]
Looking at the component router, components: are in the hope that it will be "restrict 'A'."

``` javascript
this.controller.$$template = '<div ' + dashCase(componentName) + '></div>';
```

But Angula1.5 is implemented in 'E'.

``` javascript
controller: controller,
controllerAs: identifierForController(options.controller) || options.controllerAs || '$ctrl',
template: makeInjectable(template),
templateUrl: makeInjectable(options.templateUrl),
transclude: options.transclude,
scope: {},
bindToController: options.bindings || {},
restrict: 'E',
require: options.require
```

This has been any issue:
https://github.com/angular/angular.js/issues/13966

Specification is like 'E'.
https://github.com/angular/angular.js/blob/master/CHANGELOG.md#breaking-changes-3

Thank you.

**Comment by tolemac** [comment]
There was a bug and it had been fixed: https://github.com/angular/angular/commit/d86be245b8c1fdbbad603d8ddeb3b5bc6278ee74

`excellalabs/ngComponentRouter` need to include the last version of angular component router.

**Comment by albatrosary** [comment]
So happy! Thanks!!

**Comment by duluca** [comment]
Updated to today's build, published on npm as version 1.4.0.

**Comment by tolemac** [comment]
Nice!

**Comment by albatrosary** [comment]
Thanks!!
