### ISSUE TITLE
This latest angular_1_router will not work as you've required two angular2 modules with it

### ISSUE THREAD

**Issue by Rab815** [excellalabs/ngComponentRouter#2]
Lines included with this release require 2 angular2 modules.  These won't be present if trying to just use ngComponentRouters functionality without the use of angular 2
var lang_1 = require1('angular2/src/facade/lang');
var core_1 = require1('angular2/core');

**Comment by albatrosary** [comment]
Right now, I tried to build in step. When build, the module did not enter.

``` bash
git clone git@github.com:angular/angular.git angular2
cd angular2 and npm install
gulp buildRouter.dev
```

Line of problem:

``` javascript
exports.ComponentInstruction = ComponentInstruction;
var lang_1 = require1('angular2/src/facade/lang');
var url_parser_1 = require1('./url_parser');
```

When build:

``` javascript
exports.ComponentInstruction = ComponentInstruction;
var url_parser_1 = require('./url_parser');
var TouchMap = (function () {
```

Thank you.

**Comment by duluca** [comment]
I've accepted the pull request and published the new version. I'm using https://github.com/duluca/angular1.5-starter to test this router. If you're still seeing issues could you please send a 'repro' PR to that project?

**Comment by albatrosary** [comment]
@duluca, I understand.
Try using https://github.com/duluca/angular1.5-starter.

**Comment by duluca** [comment]
@albatrosary For me it works, what issue do you see?

**Comment by albatrosary** [comment]
@duluca The problem is not.
Curious https://github.com/duluca/angular1.5-starter, took a look.
That served as a reference in my development.

And https://github.com/duluca/angular1.5-starter also ngcomponentrouter@1.4.0 it had become error. Was good :-)

I write the "issue/PR" to https://github.com/duluca/angular1.5-starter if there something

 Thank you.

**Comment by duluca** [comment]
Awesome, thanks!
