### ISSUE TITLE
Issue with templateUrl

### ISSUE THREAD

**Issue by olee** [excellalabs/ngComponentRouter#4]
Hi, could you try to update this code?
I was using it but encountered a critical issue which was fixed in latest versions in the original.
See here for the [issue](https://github.com/angular/angular/issues/4633) and the [merge](https://github.com/angular/angular/pull/6978) that fixed it.

It would be really awesome if you could fix this asap or give me a pointer on how to do that!

**Comment by olee** [comment]
Sorry, just noticed that this already seems to be fixed in the repository and that new version just hasn't been added to npm yet...

**Comment by duluca** [comment]
I did publish the latest version as of yesterday on npm
