### ISSUE TITLE
Arrow function in code

### ISSUE THREAD

**Issue by lifenautjoe** [excellalabs/ngComponentRouter#6]
Why is there an arrow function in the compiled code  [`here`](https://github.com/excellalabs/ngComponentRouter/blob/master/angular_1_router.js#L3093)

This should be changed to 

``` js
            config = angular.extend({}, config, { loader: $injector.invoke(loader) })
```

**Comment by diegohaz** [comment]
I ran into this problem right now while trying to build my project.

**Comment by lifenautjoe** [comment]
@diegohaz , I have forked the repository [here](https://github.com/thefabulousdev/ngComponentRouter)  , if you are using `jspm` you can install this from there for now.

@duluca could you accept the PR?

**Comment by duluca** [comment]
@fabulousdev I saw you closed your PR, building from latest Angular commit didn't work?

**Comment by lifenautjoe** [comment]
@duluca it didn't, it somehow was requiring other files to be present relative to the script

**Comment by duluca** [comment]
That used to be an issue, I thought they fixed it. I'll pull and try as
well.
On Sun, Apr 10, 2016 at 11:37 AM Joel Hernández notifications@github.com
wrote:

> @duluca https://github.com/duluca it didn't, it somehow was requiring
> other files to be present relative to the script
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/excellalabs/ngComponentRouter/issues/6#issuecomment-208004289
> 
> ## 
> 
> Best,

Doguhan Uluca
540-257-5143

**Comment by duluca** [comment]
@thefabulousdev @diegohaz published new npm package with the latest version and removal of arrow function

**Comment by diegohaz** [comment]
Thank you, @duluca 
Do you know where can I find the changelog for the original ngComponentRouter?

**Comment by duluca** [comment]
@diegohaz combination of here https://github.com/angular/angular/blob/master/CHANGELOG.md and here https://docs.google.com/document/d/150lerb1LmNLuau_a_EznPV1I1UHMTbEl61t4hZ7ZpS0
